spring.application.name=first
server.port=8081
spring.profiles.active=prod
# Database confituration (Comment)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=orclpdbuser
spring.datasource.password=isdb62
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.driver-class-name=org.postgresql.Driver # PostgreSQL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


